[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"

[context.deploy-preview]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"

[context.branch-deploy]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"
