[build]
  command = "cd frontend && yarn install && yarn build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "cd frontend && yarn install && yarn build"
  publish = "frontend/build"

[context.deploy-preview]
  command = "cd frontend && yarn install && yarn build"
  publish = "frontend/build"

[context.branch-deploy]
  command = "cd frontend && yarn install && yarn build"
  publish = "frontend/build"
